GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJpYXQiOjE3NjYzMTc1NzYsImV4cCI6MTc2NjMyMTE3Nn0.DN_-iJDC4ZForxg4OvvX-ItPZaw-shMOnFP2HV7tD33wX6kgGqVR9xIqJL8GD7qP2jq5btOHIF0X84z-_mIm8fswuHNR0xX07wLjR3QgaXKUatVIJ_4F6Cnjh4KADk6e2NiwiOpJYJ_rht09_blcVqxQQQ-tMS0jbx0TZvg25LV-JQs9CSj6GMzIUA3GLq2KRgtmquGZMz7l5FwJEmJ8BEDxaIMQ1l1BxuIshLv7TZ0zoXOE9Tqr4qBGiMpWeggWi7789VZ2PHC99_ZAEA0L9YkR6AADmwREeXbd6V85a2nIWbyVJ-WCOK8hSAYOPBByh6v-jvaNvBlZrmDfIaC3OA